/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as TournamentDoticsRouteImport } from './routes/tournament[.]ics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentDoticsRoute = TournamentDoticsRouteImport.update({
  id: '/tournament.ics',
  path: '/tournament.ics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRoute
  '/register': typeof RegisterRoute
  '/success': typeof SuccessRoute
  '/tournament.ics': typeof TournamentDoticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRoute
  '/register': typeof RegisterRoute
  '/success': typeof SuccessRoute
  '/tournament.ics': typeof TournamentDoticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organizer': typeof OrganizerRoute
  '/register': typeof RegisterRoute
  '/success': typeof SuccessRoute
  '/tournament.ics': typeof TournamentDoticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/organizer' | '/register' | '/success' | '/tournament.ics'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/organizer' | '/register' | '/success' | '/tournament.ics'
  id:
    | '__root__'
    | '/'
    | '/organizer'
    | '/register'
    | '/success'
    | '/tournament.ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizerRoute: typeof OrganizerRoute
  RegisterRoute: typeof RegisterRoute
  SuccessRoute: typeof SuccessRoute
  TournamentDoticsRoute: typeof TournamentDoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournament.ics': {
      id: '/tournament.ics'
      path: '/tournament.ics'
      fullPath: '/tournament.ics'
      preLoaderRoute: typeof TournamentDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizerRoute: OrganizerRoute,
  RegisterRoute: RegisterRoute,
  SuccessRoute: SuccessRoute,
  TournamentDoticsRoute: TournamentDoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
